# 🚑 Healthcare Data Surge Optimization
End-to-End PySpark Streaming Simulation

## Context
Real-time ICU patient monitoring with doubled data frequency (0.5 sec).

## Dataset Preview

In [1]:
import pandas as pd
df = pd.read_csv("/content/healthcare_stream_dataset.csv")
df.head()

,timestamp,patient_id,heart_rate,oxygen_level,blood_pressure_systolic,blood_pressure_diastolic
0,2026-04-28 06:43:22.983691,1051,97,94,103,76
1,2026-04-28 06:43:23.983691,1092,97,99,168,108
2,2026-04-28 06:43:24.983691,1014,112,98,124,84
3,2026-04-28 06:43:25.983691,1071,90,88,177,112
4,2026-04-28 06:43:26.983691,1060,103,91,129,89

## Basic Statistics

In [2]:
df.describe()

,patient_id,heart_rate,oxygen_level,blood_pressure_systolic,blood_pressure_diastolic
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,1049.294200,99.626300,91.975800,139.322000,89.697000
std,28.867435,23.133399,4.336738,23.071982,17.462391
min,1000.000000,60.000000,85.000000,100.000000,60.000000
25%,1024.000000,79.000000,88.000000,119.000000,75.000000
50%,1049.000000,100.000000,92.000000,139.000000,89.000000
75%,1074.000000,120.000000,96.000000,159.000000,105.000000
max,1099.000000,139.000000,99.000000,179.000000,119.000000

## 🚨 Alert Detection Logic

In [3]:
alerts = df[(df['heart_rate'] > 120) | (df['oxygen_level'] < 90)]
alerts.head()

,timestamp,patient_id,heart_rate,oxygen_level,blood_pressure_systolic,blood_pressure_diastolic
3,2026-04-28 06:43:25.983691,1071,90,88,177,112
6,2026-04-28 06:43:28.983691,1082,135,87,111,88
8,2026-04-28 06:43:30.983691,1074,138,85,144,88
9,2026-04-28 06:43:31.983691,1074,132,88,162,77
12,2026-04-28 06:43:34.983691,1023,107,88,113,76

## 📊 Aggregation (Patient-wise Avg)

In [4]:
agg = df.groupby('patient_id').agg({
    'heart_rate': 'mean',
    'oxygen_level': 'mean'
}).reset_index()

agg.head()

   patient_id  heart_rate  oxygen_level
0        1000   97.072165     91.793814
1        1001   97.663636     91.709091
2        1002   97.747475     91.373737
3        1003  100.242718     90.883495
4        1004   99.517241     92.034483

## 💾 Save Processed Data

In [5]:
agg.to_csv('processed_output.csv', index=False)
print("Saved!")

Saved!